flask_editablesite/user/models.py
# -*- coding: utf-8 -*-

from flask import current_app as app
from flask_login import UserMixin
from sqlalchemy import event

from flask_editablesite.extensions import bcrypt
from flask_editablesite.database import (
    Column,
    db,
    Model,
    SurrogatePK,
    TimeStamped,
    Confirmable,
    update_timestamps_before_insert,
    update_timestamps_before_update,
    update_confirmedat_before_save,
)


class User(UserMixin, SurrogatePK, TimeStamped, Confirmable, Model):
    __tablename__ = 'users'

    email = Column(db.String(255), unique=True, nullable=False)
    password = Column(db.String(255), nullable=True)
    first_name = Column(db.String(255), nullable=True)
    last_name = Column(db.String(255), nullable=True)

    def __init__(self, email, password=None, **kwargs):
        db.Model.__init__(self, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        if self.first_name and self.last_name:
            return "{0} {1}".format(self.first_name, self.last_name)

        return ""

    @property
    def full_name_or_email(self):
        return self.full_name or self.email

    def __repr__(self):
        return '{0} <{1}>'.format(self.full_name, self.email)

    @classmethod
    def sessionstore_user(cls):
        """
        A dummy user object to represent the logged-in user when
        we're set to 'sessionstore' instead of 'db'.
        """

        return cls(
            email=app.config['SESSIONSTORE_USER_EMAIL'],
            first_name=app.config['SESSIONSTORE_USER_FIRST_NAME'],
            last_name=app.config['SESSIONSTORE_USER_LAST_NAME'],
            active=True)


event.listen(User, 'before_insert', update_timestamps_before_insert)
event.listen(User, 'before_update', update_timestamps_before_update)

event.listen(User, 'before_insert', update_confirmedat_before_save)
event.listen(User, 'before_update', update_confirmedat_before_save)

flask_editablesite/editable/forms.py
# -*- coding: utf-8 -*-
from wtforms import (TextField, TextAreaField, HiddenField, FieldList,
                     FormField, DateField)
from wtforms_components import TimeField
from wtforms.validators import DataRequired

from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed


class TextEditForm(Form):
    content = TextField('Content', validators=[DataRequired()])


class TextOptionalEditForm(Form):
    content = TextField('Content', validators=[])


class LongTextEditForm(Form):
    content = TextAreaField('Content', validators=[DataRequired()])


class LongTextOptionalEditForm(Form):
    content = TextAreaField('Content', validators=[])


class ImageEditForm(Form):
    image = FileField('Image', validators=[
        DataRequired(),
        FileAllowed(
            ('gif', 'jpg', 'jpeg', 'png'),
            ('Only image files (gif, jpg, png) can be uploaded '
                'for this field'))])


class ImageOptionalEditForm(Form):
    image = FileField('Image', validators=[
        FileAllowed(
            ('gif', 'jpg', 'jpeg', 'png'),
            ('Only image files (gif, jpg, png) can be uploaded for '
                'this field'))])


class DateEditForm(Form):
    content = DateField('Date', format='%d %b %Y', validators=[
        DataRequired()])


class DateOptionalEditForm(Form):
    content = DateField('Date', format='%d %b %Y', validators=[])


class TimeEditForm(Form):
    content = TimeField('Time', validators=[DataRequired()])


class TimeOptionalEditForm(Form):
    content = TimeField('Time', validators=[])


class ReorderItemForm(Form):
    identifier = HiddenField(validators=[])
    weight = HiddenField(validators=[])


class ReorderForm(Form):
    items = FieldList(FormField(ReorderItemForm))

flask_editablesite/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""

from flask import Flask, render_template

from flask_editablesite.settings import ProdConfig
from flask_editablesite.assets import assets
from flask_editablesite.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    mail,
    sess,
    migrate,
    debug_toolbar,
    thumb,
)
from flask_editablesite.public.views import blueprint as public_bp
from flask_editablesite.editable.views import blueprint as editable_bp


def create_app(config_object=ProdConfig):
    """An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_loggers(app)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    thumb.init_app(app)

    if app.config.get('SESSION_TYPE'):
        sess.init_app(app)

    return None


def register_blueprints(app):
    app.register_blueprint(public_bp)
    app.register_blueprint(editable_bp)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return (render_template("{0}.html".format(error_code)),
                error_code)
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_loggers(app):
    import logging
    from logging.handlers import SMTPHandler

    log_formatter = logging.Formatter(
        '%(levelname)s %(asctime)s %(message)s',
        '[%Y-%m-%d %H:%M:%S]')

    if len(app.logger.handlers):
        app.logger.handlers[0].setFormatter(log_formatter)

    if not app.debug:
        stream_handler = logging.StreamHandler()
        stream_handler.setFormatter(log_formatter)
        app.logger.addHandler(stream_handler)
        app.logger.setLevel(logging.INFO)

        if app.config['ADMINS']:
            smtp_handler_args = {}
            if app.config.get('MAIL_USERNAME'):
                smtp_handler_args['credentials'] = (
                    app.config['MAIL_USERNAME'],
                    app.config['MAIL_PASSWORD'])
                smtp_handler_args['secure'] = ()

            mail_handler = SMTPHandler(
                (app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                app.config['MAIL_DEFAULT_SENDER'],
                app.config['ADMINS'],
                ('[%s] Error report' % app.config['SITE_NAME']),
                **smtp_handler_args)
            mail_handler.setLevel(logging.ERROR)
            mail_handler.setFormatter(
                logging.Formatter(app.config['ERROR_MAIL_FORMAT']))
            app.logger.addHandler(mail_handler)

        app.logger.info('flask_editablesite startup')

flask_editablesite/contentblock/__init__.py
# -*- coding: utf-8 -*-

flask_editablesite/editable/__init__.py
# -*- coding: utf-8 -*-

flask_editablesite/editable/views.py
from datetime import datetime
from glob import glob
from operator import itemgetter
import os
from sqlalchemy.exc import IntegrityError

from flask import current_app as app
from flask import (abort, Blueprint, flash, url_for, redirect, request,
                   session, Response)
from flask_login import login_required, current_user
from flask_transfer import Transfer
from werkzeug import secure_filename
from flask_wtf import Form

from flask_editablesite.extensions import db
from flask_editablesite.editable.forms import (
    TextEditForm, LongTextEditForm, DateEditForm, TimeEditForm,
    ImageEditForm, ReorderForm)
from flask_editablesite.editable.utils import get_model_class
from flask_editablesite.editable.sample_images import (
    placeholder_or_random_sample_image,)
from flask_editablesite.editable.sample_text import (
    placeholder_or_random_sample_text,)
from flask_editablesite.utils import flash_errors


blueprint = Blueprint('editable', __name__, static_folder="../static")


def delete_image_orig(image_orig):
    """Deletes the specified old image."""

    filepath = os.path.abspath(
        os.path.join(
            app.config['MEDIA_FOLDER'],
            image_orig))

    if os.path.exists(filepath):
        os.remove(filepath)

    glob_filepath_split = os.path.splitext(
        os.path.join(
            app.config['MEDIA_THUMBNAIL_FOLDER'],
            image_orig))
    glob_filepath = glob_filepath_split[0]
    glob_matches = glob('%s*' % glob_filepath)

    for fp in glob_matches:
        if os.path.exists(fp):
            os.remove(fp)


def update_submit_handler(model_name, model_identifier,
                          model_identifier_int, title_field_name,
                          content, model, field_name,
                          is_autosave=False, image_orig=None):
    """Generic submit handler for the update functions."""

    try:
        if app.config.get('USE_SESSIONSTORE_NOT_DB'):
            if session.get(model_name) is None:
                session[model_name] = {}

            if not model_identifier_int:
                if not (session.get(model_name, {})
                        .get(model_identifier, None)):
                    session[model_name][model_identifier] = {
                        title_field_name: getattr(
                            model, title_field_name)}

            session[model_name][(
                model_identifier_int or model_identifier
            )][field_name] = content
        else:
            setattr(model, field_name, content)
            model.save()

            if (
                image_orig
                and (image_orig != app.config[
                    'EDITABLE_PLACEHOLDER_IMAGE_RELATIVE_PATH'])):
                delete_image_orig(image_orig)

        app.logger.info('{0} updated: {1}; user: {2}'.format(
            model_name.replace('_', ' ').capitalize(),
            model, current_user))

        if is_autosave:
            return Response('OK')
        else:
            flash("{0} has been updated.".format(
                getattr(model, title_field_name)), 'success')
            return None
    except IntegrityError:
        db.session.rollback()

        if is_autosave:
            return Response('ERROR', 400)
        else:
            flash("Error updating {0}.".format(
                getattr(model, title_field_name)), 'danger')
            return None


def text_update_func(model_name, field_name, model_identifier,
                     is_autosave=False):
    try:
        v = app.config['EDITABLE_MODELS'][model_name]
    except KeyError:
        abort(404)

    if ('long_text_fields' in v) and (field_name in v['long_text_fields']):
        is_long_text = True
    elif ('text_fields' in v) and (field_name in v['text_fields']):
        is_long_text = False
    else:
        abort(404)

    try:
        model_classpath = v['classpath']
    except KeyError:
        raise ValueError((
            'No class path defined in app config\'s '
            'EDITABLE_MODELS for model name "{0}"').format(
                model_name))

    try:
        identifier_field_name = v['identifier_field']
    except KeyError:
        raise ValueError((
            'No identifier field defined in app config\'s '
            'EDITABLE_MODELS for model name "{0}"').format(
                model_name))

    try:
        title_field_name = v['title_field']
    except KeyError:
        raise ValueError((
            'No title field defined in app config\'s '
            'EDITABLE_MODELS for model name "{0}"').format(
                model_name))

    model_class = get_model_class(model_classpath, model_name)

    try:
        model_identifier_int = int(model_identifier)
    except ValueError:
        model_identifier_int = None

    filter_by_kwargs = {
        identifier_field_name: model_identifier,
        'active': True}
    model = None

    if app.config.get('USE_SESSIONSTORE_NOT_DB'):
        model_store = session.get(model_name, None)
        model_dict = None

        if model_store and (type(model_store).__name__ == 'list'):
            try:
                model_dict = model_store[model_identifier_int]
            except KeyError:
                pass
        elif model_store and (type(model_store).__name__ == 'dict'):
            model_dict = model_store.get(model_identifier, None)

        if model_dict:
            model = model_class(**model_dict)
    else:
        model = (
            model_class.query
                       .filter_by(**filter_by_kwargs)
                       .first())

    if not model:
        try:
            model = model_class.default_content()[model_identifier]
        except KeyError:
            abort(404)

    form = is_long_text and LongTextEditForm() or TextEditForm()

    if form.validate_on_submit():
        content = form.content.data

        ret = update_submit_handler(
            model_name=model_name,
            model_identifier=model_identifier,
            model_identifier_int=model_identifier_int,
            title_field_name=title_field_name,
            content=content,
            model=model,
            field_name=field_name,
            is_autosave=is_autosave)

        if ret:
            return ret
    else:
        if is_autosave:
            return Response('ERROR', 400)
        else:
            flash_errors(form)

    return redirect(url_for("public.home"))


@blueprint.route(
    "/text-update/<model_name>/<field_name>/<model_identifier>/",
    methods=["POST"])
@login_required
def text_update(model_name, field_name, model_identifier):
    return text_update_func(
        model_name=model_name,
        field_name=field_name,
        model_identifier=model_identifier)


@blueprint.route(
    "/text-update-autosave/<model_name>/<field_name>/<model_identifier>/",
    methods=["POST"])
@login_required
def text_update_autosave(model_name, field_name, model_identifier):
    return text_update_func(
        model_name=model_name,
        field_name=field_name,
        model_identifier=model_identifier,
        is_autosave=True)


def date_update_func(model_name, field_name, model_identifier,
                     is_autosave=False):
    try:
        v = app.config['EDITABLE_MODELS'][model_name]
    except KeyError:
        abort(404)

    if not(('date_fields' in v) and (field_name in v['date_fields'])):
        abort(404)

    try:
        model_classpath = v['classpath']
    except KeyError:
        raise ValueError((
            'No class path defined in app config\'s '
            'EDITABLE_MODELS for model name "{0}"').format(
                model_name))

    try:
        identifier_field_name = v['identifier_field']
    except KeyError:
        raise ValueError((
            'No identifier field defined in app '
            'config\'s EDITABLE_MODELS for model name "{0}"').format(
                model_name))

    try:
        title_field_name = v['title_field']
    except KeyError:
        raise ValueError((
            'No title field defined in app '
            'config\'s EDITABLE_MODELS for model name "{0}"').format(
                model_name))

    model_class = get_model_class(model_classpath, model_name)

    try:
        model_identifier_int = int(model_identifier)
    except ValueError:
        model_identifier_int = None

    filter_by_kwargs = {
        identifier_field_name: model_identifier,
        'active': True}
    model = None

    if app.config.get('USE_SESSIONSTORE_NOT_DB'):
        model_store = session.get(model_name, None)
        model_dict = None

        if model_store and (type(model_store).__name__ == 'list'):
            try:
                model_dict = model_store[model_identifier_int]
            except KeyError:
                pass
        elif model_store and (type(model_store).__name__ == 'dict'):
            model_dict = model_store.get(model_identifier, None)

        if model_dict:
            model = model_class(**model_dict)
    else:
        model = (
            model_class.query
                       .filter_by(**filter_by_kwargs)
                       .first())

    if not model:
        try:
            model = model_class.default_content()[model_identifier]
        except KeyError:
            abort(404)

    form = DateEditForm()

    if form.validate_on_submit():
        content = form.content.data
        if content and app.config.get('USE_SESSIONSTORE_NOT_DB'):
            content = content.strftime('%Y-%m-%d')

        ret = update_submit_handler(
            model_name=model_name,
            model_identifier=model_identifier,
            model_identifier_int=model_identifier_int,
            title_field_name=title_field_name,
            content=content,
            model=model,
            field_name=field_name,
            is_autosave=is_autosave)

        if ret:
            return ret
    else:
        if is_autosave:
            return Response('ERROR', 400)
        else:
            flash_errors(form)

flask_editablesite/event/__init__.py
# -*- coding: utf-8 -*-

flask_editablesite/gallery/__init__.py
# -*- coding: utf-8 -*-

flask_editablesite/user/__init__.py
# -*- coding: utf-8 -*-

flask_editablesite/templates/macros/dante.html
{% macro field(f, field_id='', label_class="control-label hidden") %}
<div class="form-group {% if f.errors %} has-error{% endif %}">
  <label for="{{ field_id }}">{{ f.label }}</label>

  {% if f.flags.required and not required in kwargs %}
  {% set kwargs = dict(required=True, **kwargs) %}
  {% endif %}

  {{f(class="form-control", id=field_id, **kwargs)|safe}}

  <div id="{{ field_id }}-wysiwyg" class="dante-editable editable-wrapper" style="min-height: 34px"></div>

  {%- if f.errors %}
    {%- for error in f.errors %}
      <p class="help-block">{{error}}</p>
    {%- endfor %}
  {%- elif f.description -%}
    <p class="help-block">{{f.description|safe}}</p>
  {%- endif %}
</div>
{% endmacro %}

flask_editablesite/templates/macros/date_pick.html
{% import 'macros/heading.html' as heading %}

{% macro form(model_name, field_name, model_identifier, form, class='datepicker-enable', placeholder='Pick your date', wrap_element_start='', wrap_element_end='') %}

{% set model_identifier = model_identifier|string %}

{% with field_id = (model_name + '-' + field_name + '-' + model_identifier) %}

<form id="date-pick-form-{{ field_id }}" method="POST" class="form-editable{% if wrap_element_start == '<span>' %} form-editable-inline{% endif %}" action="{{ url_for('editable.date_update', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-url="{{ url_for('editable.date_update_autosave', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-field-id="{{ field_id }}">
  {{ form.hidden_tag() }}

  {% if wrap_element_start == '<span>' %}
    {% set wrap_el_type = 'span' %}
  {% else %}
    {% set wrap_el_type = 'div' %}
  {% endif %}

  <{{ wrap_el_type }} class="title-image-wrapper"><{{ wrap_el_type }} class="editable-wrapper">
    {{ heading.field(form.content, field_id=field_id, class=class, placeholder=placeholder, wrap_element_start=wrap_element_start, wrap_element_end=wrap_element_end) }}
  </{{ wrap_el_type }}></{{ wrap_el_type }}>

  <div class="form-editable-button">
  <button type="submit" class="btn btn-default">Update</button>
  </div>

  {% include 'autosave_status.html' %}
</form>

{% endwith %}

{% endmacro %}

flask_editablesite/templates/macros/heading.html
{% macro field(field, field_id='', class='h2', placeholder='Type your title', label_class='control-label hidden', wrap_element_start='', wrap_element_end='') %}

{% if wrap_element_start == '<span>' %}
  {% set wrap_el_type = 'span' %}
{% else %}
  {% set wrap_el_type = 'div' %}
{% endif %}

<{{ wrap_el_type }} class="form-group {% if field.errors %} has-error{% endif %}">
  <label for="{{ field.id }}">{{field.label}}</label>

  {%- if wrap_element_start %}
  {{ wrap_element_start|safe }}
  {%- endif %}

  {% if field.flags.required and not required in kwargs %}
  {% set kwargs = dict(required=True, **kwargs) %}
  {% endif %}

  {{field(class=class, id=field_id, placeholder=placeholder, **kwargs)|safe}}

  {%- if wrap_element_end %}
  {{ wrap_element_end|safe }}
  {%- endif %}

  {%- if field.errors %}
    {%- for error in field.errors %}
      <p class="help-block">{{error}}</p>
    {%- endfor %}
  {%- elif field.description -%}
    <p class="help-block">{{field.description|safe}}</p>
  {%- endif %}
</{{ wrap_el_type }}>
{% endmacro %}

flask_editablesite/templates/macros/hiddenfield.html
{% macro field(field, label_class='control-label hidden') %}

<div class="form-group {% if field.errors %} has-error{% endif %}" style="margin: 0">
  {{field.label(class=label_class)|safe}}

  {{field(**kwargs)|safe}}

  {%- if field.errors %}
    {%- for error in field.errors %}
      <p class="help-block">{{error}}</p>
    {%- endfor %}
  {%- elif field.description -%}
    <p class="help-block">{{field.description|safe}}</p>
  {%- endif %}
</div>
{% endmacro %}

flask_editablesite/templates/macros/image.html
{% import 'macros/heading.html' as heading %}

{% macro form(model_name, field_name, model_identifier, form, image_url, class='img-responsive', alt='', placeholder='Upload your image') %}

{% set model_identifier = model_identifier|string %}

{% with field_id = (model_name + '-' + field_name + '-' + model_identifier) %}

<form id="image-form-{{ field_id }}" method="POST" class="form-editable dropzone-to-enable" action="{{ url_for('editable.image_update', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" enctype="multipart/form-data">
  {{ form.hidden_tag() }}

  <div class="title-image-wrapper"><div class="editable-wrapper">
    <div class="fallback">
    {{ heading.field(form.image, placeholder=placeholder) }}
    </div>

    <img class="{{ class }}" src="{{ image_url }}" alt="{{ alt }}">
  </div></div>

  <div class="form-editable-button">
  <button type="submit" class="btn btn-default">Upload</button>
  </div>

  {% include 'autosave_status.html' %}
</form>

{% endwith %}

{% endmacro %}

flask_editablesite/templates/macros/rich_text.html
{% import 'macros/dante.html' as dante %}

{% macro form(model_name, field_name, model_identifier, form, placeholder='Type your content') %}

{% set model_identifier = model_identifier|string %}

{% with field_id = (model_name + '-' + field_name + '-' + model_identifier) %}

<form id="rich-text-form-{{ field_id }}" method="POST" class="form-editable" action="{{ url_for('editable.text_update', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-url="{{ url_for('editable.text_update_autosave', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-field-id="{{ field_id }}">
  {{ form.hidden_tag() }}

  {{ dante.field(form.content, field_id=field_id) }}

  <div class="form-editable-button">
  <button type="submit" class="btn btn-default">Update</button>
  </div>

  {% include 'autosave_status.html' %}
</form>

{% endwith %}

{% endmacro %}

flask_editablesite/templates/macros/short_text.html
{% import 'macros/heading.html' as heading %}

{% macro form(model_name, field_name, model_identifier, form, class='h2', placeholder='Type your title', wrap_element_start='', wrap_element_end='') %}

{% set model_identifier = model_identifier|string %}

{% with field_id = (model_name + '-' + field_name + '-' + model_identifier) %}

<form id="short-text-form-{{ field_id }}" method="POST" class="form-editable{% if wrap_element_start == '<span>' %} form-editable-inline{% endif %}" action="{{ url_for('editable.text_update', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-url="{{ url_for('editable.text_update_autosave', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-field-id="{{ field_id }}">
  {{ form.hidden_tag() }}

  {% if wrap_element_start == '<span>' %}
    {% set wrap_el_type = 'span' %}
  {% else %}
    {% set wrap_el_type = 'div' %}
  {% endif %}

  <{{ wrap_el_type }} class="title-image-wrapper"><{{ wrap_el_type }} class="editable-wrapper">
    {{ heading.field(form.content, field_id=field_id, class=class, placeholder=placeholder, wrap_element_start=wrap_element_start, wrap_element_end=wrap_element_end) }}
  </{{ wrap_el_type }}></{{ wrap_el_type }}>

  <div class="form-editable-button">
  <button type="submit" class="btn btn-default">Update</button>
  </div>

  {% include 'autosave_status.html' %}
</form>

{% endwith %}

{% endmacro %}

flask_editablesite/templates/macros/time_pick.html
{% import 'macros/heading.html' as heading %}

{% macro form(model_name, field_name, model_identifier, form, class='timepicker-enable', placeholder='Pick your time', wrap_element_start='', wrap_element_end='') %}

{% set model_identifier = model_identifier|string %}

{% with field_id = (model_name + '-' + field_name + '-' + model_identifier) %}

<form id="time-pick-form-{{ field_id }}" method="POST" class="form-editable{% if wrap_element_start == '<span>' %} form-editable-inline{% endif %}" action="{{ url_for('editable.time_update', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-url="{{ url_for('editable.time_update_autosave', model_name=model_name, field_name=field_name, model_identifier=model_identifier) }}" data-autosave-field-id="{{ field_id }}">
  {{ form.hidden_tag() }}

  {% if wrap_element_start == '<span>' %}
    {% set wrap_el_type = 'span' %}
  {% else %}
    {% set wrap_el_type = 'div' %}
  {% endif %}

  <{{ wrap_el_type }} class="title-image-wrapper"><{{ wrap_el_type }} class="editable-wrapper">
    {{ heading.field(form.content, field_id=field_id, class=class, placeholder=placeholder, wrap_element_start=wrap_element_start, wrap_element_end=wrap_element_end) }}
  </{{ wrap_el_type }}></{{ wrap_el_type }}>

  <div class="form-editable-button">
  <button type="submit" class="btn btn-default">Update</button>
  </div>

  {% include 'autosave_status.html' %}
</form>

{% endwith %}

{% endmacro %}